-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 21:48:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `idUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUSUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SALA` (
  `idSALA` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idSALA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MENSAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MENSAJE` (
  `idMENSAJE` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `contenido` VARCHAR(200) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `idSala` INT NOT NULL,
  PRIMARY KEY (`idMENSAJE`),
  CONSTRAINT `usuario_mensaje`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sala_mensaje`
    FOREIGN KEY (`idSala`)
    REFERENCES `SALA` (`idSALA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `usuario_mensaje_idx` ON `MENSAJE` (`idUsuario` ASC);

CREATE INDEX `sala_mensaje_idx` ON `MENSAJE` (`idSala` ASC);


-- -----------------------------------------------------
-- Table `SALA_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SALA_USUARIO` (
  `idSALA_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idSala` INT NOT NULL,
  PRIMARY KEY (`idSALA_USUARIO`),
  CONSTRAINT `id_sala`
    FOREIGN KEY (`idSala`)
    REFERENCES `SALA` (`idSALA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_sala_idx` ON `SALA_USUARIO` (`idSala` ASC);

CREATE INDEX `id_usuario_idx` ON `SALA_USUARIO` (`idUsuario` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
