-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 17:20:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `idUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `ultima_conexion` DATETIME NULL,
  PRIMARY KEY (`idUSUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SALA` (
  `idSALA` INT NOT NULL AUTO_INCREMENT,
  `descripción` VARCHAR(100) NULL,
  `imagen` VARCHAR(250) NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSALA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MENSAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MENSAJE` (
  `idMENSAJE` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `contenido` VARCHAR(200) NOT NULL,
  `idSala` INT NOT NULL,
  `estado_eliminado` TINYINT NOT NULL,
  `fecha_envio` DATETIME NOT NULL,
  `nombreEmisor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMENSAJE`),
  CONSTRAINT `sala_mensaje`
    FOREIGN KEY (`idSala`)
    REFERENCES `mydb`.`SALA` (`idSALA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_mensaje`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `sala_mensaje_idx` ON `mydb`.`MENSAJE` (`idSala` ASC);

CREATE INDEX `usuario_mensaje_idx` ON `mydb`.`MENSAJE` (`idUsuario` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`SALA_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SALA_USUARIO` (
  `idSALA_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `idSala` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idSALA_USUARIO`),
  CONSTRAINT `id_sala`
    FOREIGN KEY (`idSala`)
    REFERENCES `mydb`.`SALA` (`idSALA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_sala_idx` ON `mydb`.`SALA_USUARIO` (`idSala` ASC);

CREATE INDEX `id_usuario_idx` ON `mydb`.`SALA_USUARIO` (`idUsuario` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
